kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "..fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: [ "replicasets", "deployments" ]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: [ "jobs", "cronjobs" ]
  verbs: ["get", "watch", "list"]
